-- add darkmod configuration
pfUI:UpdateConfig("darkmod", nil, "movechat", "1")
pfUI:UpdateConfig("darkmod", nil, "darkline", "1")
pfUI:UpdateConfig("darkmod", nil, "viewport", "1")
pfUI:UpdateConfig("darkmod", nil, "chatbox", "1")
pfUI:UpdateConfig("darkmod", nil, "castbar", "1")
pfUI:UpdateConfig("darkmod", nil, "movexp", "1")
pfUI:UpdateConfig("darkmod", nil, "movebuff", "1")
pfUI:UpdateConfig("darkmod", nil, "minimap", "1")
pfUI:UpdateConfig("darkmod", nil, "actionbar", "1")
pfUI:UpdateConfig("darkmod", nil, "unitframe", "1")
pfUI:UpdateConfig("darkmod", nil, "tracking", "1")
pfUI:UpdateConfig("darkmod", nil, "lootrolls", "1")
pfUI:UpdateConfig("darkmod", nil, "topbg", "1")

-- add darkmod module to pfUI
pfUI:RegisterModule("darkmod", function ()

  local CreateGUIEntry = pfUI.gui.CreateGUIEntry
  local CreateConfig = pfUI.gui.CreateConfig

  -- creating the profile of the darkmod.
  -- it's generated by using the `/share` command.
  pfUI_profiles["pfUI [|cff33aa88darkmod|r]"] = {
	["darkmod"] = {
		["chatbox"] = "0",
		["movechat"] = "0",
		["castbar"] = "0",
		["darkerframes"] = "0",
		["actionbar"] = "0",
		["minimap"] = "0",
		["viewport"] = "0",
		["topbg"] = "0",
		["movexp"] = "0",
		["darkline"] = "0",
		["lootrolls"] = "0",
		["movebuff"] = "0",
		["tracking"] = "1",
		["unitframe"] = "0",
	  },
	  ["unitframes"] = {
		["grouptarget"] = {
		  ["verticalbar"] = "1",
		  ["txthpleft"] = "none",
		  ["width"] = "50",
		  ["txthpcenter"] = "namehealthbreak",
		  ["rainbowbar_orientation"] = "HORIZONTAL",
		  ["overhealperc"] = "0",
		  ["txthpright"] = "none",
		  ["height"] = "35",
		},
		["rainbowbar_tex_fixed"] = "0",
		["ptarget"] = {
		  ["portrait3d_position"] = "0.00,0.00,0.00",
		  ["pbartexture"] = "Interface\\AddOns\\pfUI\\img\\bar_gradient",
		  ["visible"] = "1",
		  ["width"] = "110",
		  ["bartexture"] = "Interface\\AddOns\\pfUI\\img\\bar_gradient",
		  ["portrait3d_scale"] = "1",
		  ["portrait3d_facing"] = "0",
		  ["portrait3d_anim_option"] = "1.0,3.5",
		  ["portrait3d_alpha"] = "0.1",
		  ["faderange"] = "1",
		  ["overhealperc"] = "0",
		  ["portrait3d_camera"] = "0",
		  ["height"] = "32",
		  ["rainbowbar_orientation"] = "HORIZONTAL",
		  ["portrait3d_anim"] = "0",
		},
		["clickcast3"] = "Ritual of Summoning",
		["target"] = {
		  ["txthpleft"] = "healthdyn",
		  ["rainbowbar_orientation"] = "HORIZONTAL",
		  ["rainbowbar"] = "0",
		  ["portrait3d_position"] = "0.00,0.00,0.00",
		  ["clickcast"] = "1",
		  ["pspace"] = "0",
		  ["portrait3d_scale"] = "1",
		  ["pheight"] = "15",
		  ["txtpowerleft"] = "powerdyn",
		  ["height"] = "35",
		  ["buffsize"] = "16",
		  ["faderange"] = "1",
		  ["portrait3d_facing"] = "0",
		  ["hitindicator"] = "1",
		  ["portrait3d_anim_option"] = "1.0,3.5",
		  ["portrait3d_alpha"] = "0.1",
		  ["buffs"] = "TOPRIGHT",
		  ["portrait3d_camera"] = "0",
		  ["txthpright"] = "unitrev",
		  ["showPVP"] = "1",
		  ["overhealperc"] = "0",
		  ["width"] = "215",
		  ["portrait3d_anim"] = "0",
		},
		["clickcast_alt"] = "Unending Breath",
		["clickcast2_shift"] = "Soulstone Resurrection",
		["player"] = {
		  ["rainbowbar_orientation"] = "HORIZONTAL",
		  ["rainbowbar"] = "0",
		  ["portrait3d_position"] = "0.00,0.00,0.00",
		  ["width"] = "215",
		  ["squareaggro"] = "1",
		  ["customcolor"] = "0,0,0,1",
		  ["txtpowerright"] = "powerdyn",
		  ["customfade"] = "1",
		  ["squarecombat"] = "1",
		  ["clickcast"] = "1",
		  ["rainbowbar_reverse"] = "1",
		  ["manatick"] = "1",
		  ["pspace"] = "0",
		  ["custombg"] = "1",
		  ["cooldown_anim"] = "1",
		  ["faderange"] = "1",
		  ["portrait3d_enable"] = "1",
		  ["portrait3d_scale"] = "1",
		  ["custompbgcolor"] = "0,0,0,1",
		  ["buffs"] = "off",
		  ["buffsize"] = "18",
		  ["portrait3d_facing"] = "0",
		  ["hitindicator"] = "1",
		  ["portrait3d_anim_option"] = "1.0,3.5",
		  ["portrait3d_alpha"] = "0.10",
		  ["custompbg"] = "1",
		  ["showPVP"] = "1",
		  ["overhealperc"] = "0",
		  ["portrait3d_camera"] = "0",
		  ["debuffs"] = "off",
		  ["custombgcolor"] = "0.2,0.1,0.1,1",
		  ["height"] = "35",
		  ["showPVPMinimap"] = "1",
		  ["pheight"] = "15",
		  ["customfullhp"] = "1",
		  ["portrait3d_anim"] = "0",
		},
		["clickcast2_ctrl"] = "Devour Magic",
		["customfade"] = "1",
		["focus"] = {
		  ["txthpleft"] = "name",
		  ["rainbowbar_orientation"] = "HORIZONTAL",
		  ["rainbowbar"] = "0",
		  ["portrait3d_position"] = "0.00,0.00,0.00",
		  ["customfade"] = "1",
		  ["customfullhp"] = "1",
		  ["debuffs"] = "off",
		  ["pheight"] = "10",
		  ["portrait3d_enable"] = "1",
		  ["portrait3d_scale"] = "1",
		  ["faderange"] = "1",
		  ["portrait3d_facing"] = "0",
		  ["portrait3d_anim_option"] = "1.0,3.5",
		  ["portrait3d_alpha"] = "0.1",
		  ["height"] = "30",
		  ["overhealperc"] = "0",
		  ["portrait3d_camera"] = "0",
		  ["buffs"] = "off",
		  ["customcolor"] = "0,0,0,1",
		  ["clickcast"] = "1",
		  ["width"] = "110",
		  ["portrait3d_anim"] = "0",
		},
		["clickcast_ctrl"] = "Fire Shield",
		["raid"] = {
		  ["verticalbar"] = "1",
		  ["txthpleft"] = "none",
		  ["defcolor"] = "0",
		  ["customfade"] = "1",
		  ["focuscolor"] = "0.6,0.4,0.2,1",
		  ["txthpcenter"] = "namehealthbreak",
		  ["energycolor"] = "0.6,0.4,0.2,1",
		  ["glowcombat"] = "1",
		  ["rainbowbar_orientation"] = "HORIZONTAL",
		  ["manacolor"] = "0.2,0.2,0.4,1",
		  ["height"] = "35",
		  ["raidfill"] = "HORIZONTAL",
		  ["txthpright"] = "none",
		  ["overhealperc"] = "0",
		  ["indicator_pos"] = "TOPRIGHT",
		  ["width"] = "40.7",
		  ["clickcast"] = "1",
		  ["customfullhp"] = "1",
		  ["customcolor"] = "0.1,0.1,0.1,1",
		  ["custom"] = "2",
		  ["ragecolor"] = "0.6,0.2,0.2,1",
		  ["raidpadding"] = "5",
		},
		["focuscolor"] = "0.6,0.4,0.2,1",
		["clickcast_shift"] = "Detect Lesser Invisibility",
		["ragecolor"] = "0.6,0.2,0.2,1",
		["rangecheck"] = "1",
		["portrait3d_anim_option"] = "1.0,3.5",
		["rainbowbar_tex_alphamode"] = "ADD",
		["pet"] = {
		  ["debuffsize"] = "22",
		  ["cooldown_anim"] = "1",
		  ["rainbowbar_orientation"] = "HORIZONTAL",
		  ["rainbowbar"] = "0",
		  ["portrait3d_position"] = "0.00,0.00,0.00",
		  ["customcolor"] = "0,0,0,1",
		  ["pspace"] = "0",
		  ["customfullhp"] = "1",
		  ["customfade"] = "1",
		  ["rainbowbar_reverse"] = "0",
		  ["pheight"] = "5",
		  ["buffperrow"] = "2",
		  ["debuffs"] = "BOTTOMRIGHT",
		  ["txthpcenter"] = "healthdyn",
		  ["faderange"] = "1",
		  ["buffsize"] = "22",
		  ["portrait3d_enable"] = "1",
		  ["portrait3d_facing"] = "0",
		  ["hitindicator"] = "1",
		  ["portrait3d_anim_option"] = "1.0,3.5",
		  ["portrait3d_alpha"] = "0.1",
		  ["buffs"] = "BOTTOMLEFT",
		  ["height"] = "32",
		  ["portrait3d_camera"] = "0",
		  ["happinessicon"] = "0",
		  ["txtpowercenter"] = "powerdyn",
		  ["debuffperrow"] = "2",
		  ["overhealperc"] = "0",
		  ["portrait3d_scale"] = "1",
		  ["portrait3d_anim"] = "0",
		},
		["custompbgcolor"] = "0.3,0.1,0.1,1",
		["group"] = {
		  ["glowcombat"] = "1",
		  ["width"] = "95",
		  ["rainbowbar_orientation"] = "HORIZONTAL",
		  ["overhealperc"] = "0",
		  ["hide_in_raid"] = "1",
		  ["txthpright"] = "health",
		  ["clickcast"] = "1",
		},
		["portrait3d_global_enable"] = "1",
		["custombgcolor"] = "0.3,0.1,0.1,1",
		["portrait3d_global_anim_enable"] = "1",
		["ttarget"] = {
		  ["rainbowbar_orientation"] = "HORIZONTAL",
		  ["rainbowbar"] = "0",
		  ["portrait3d_position"] = "0.00,0.00,0.00",
		  ["pspace"] = "0",
		  ["customfade"] = "1",
		  ["clickcast"] = "1",
		  ["customcolor"] = "0,0,0,1",
		  ["pheight"] = "-1",
		  ["faderange"] = "1",
		  ["portrait3d_facing"] = "0",
		  ["portrait3d_anim_option"] = "1.0,3.5",
		  ["portrait3d_alpha"] = "0.10",
		  ["portrait3d_camera"] = "0",
		  ["height"] = "38",
		  ["overhealperc"] = "0",
		  ["portrait3d_enable"] = "1",
		  ["portrait3d_scale"] = "1",
		  ["customfullhp"] = "1",
		  ["portrait3d_anim"] = "0",
		},
		["tttarget"] = {
		  ["verticalbar"] = "1",
		  ["rainbowbar_orientation"] = "HORIZONTAL",
		  ["portrait3d_position"] = "0.00,0.00,0.00",
		  ["width"] = "40",
		  ["pbartexture"] = "Interface\\AddOns\\pfUI\\img\\bar_gradient",
		  ["bartexture"] = "Interface\\AddOns\\pfUI\\img\\bar_gradient",
		  ["portrait3d_facing"] = "0",
		  ["portrait3d_anim_option"] = "1.0,3.5",
		  ["portrait3d_alpha"] = "0.1",
		  ["height"] = "37",
		  ["portrait3d_camera"] = "0",
		  ["overhealperc"] = "0",
		  ["portrait3d_scale"] = "1",
		  ["portrait3d_anim"] = "0",
		},
		["focustarget"] = {
		  ["verticalbar"] = "1",
		  ["portrait3d_position"] = "0.00,0.00,0.00",
		  ["pbartexture"] = "Interface\\AddOns\\pfUI\\img\\bar_gradient",
		  ["visible"] = "1",
		  ["width"] = "40",
		  ["bartexture"] = "Interface\\AddOns\\pfUI\\img\\bar_gradient",
		  ["portrait3d_scale"] = "1",
		  ["txthpcenter"] = "nameshort",
		  ["portrait3d_facing"] = "0",
		  ["portrait3d_anim_option"] = "1.0,3.5",
		  ["portrait3d_alpha"] = "0.1",
		  ["faderange"] = "1",
		  ["overhealperc"] = "0",
		  ["portrait3d_camera"] = "0",
		  ["height"] = "96",
		  ["rainbowbar_orientation"] = "HORIZONTAL",
		  ["portrait3d_anim"] = "0",
		},
		["custom"] = "2",
		["grouppet"] = {
		  ["visible"] = "0",
		  ["width"] = "95",
		  ["rainbowbar_orientation"] = "HORIZONTAL",
		  ["overhealperc"] = "0",
		},
		["manacolor"] = "0.2,0.2,0.4,1",
		["rainbowbar_global_color"] = "0",
		["customcolor"] = "0.1,0.1,0.1,1",
		["energycolor"] = "0.6,0.4,0.2,1",
		["customfullhp"] = "1",
		["buffdetect"] = "1",
		["rainbowbar_duration"] = "0.00",
	  },
	  ["screenshot"] = {
		["pvprank"] = "1",
		["levelup"] = "1",
		["loot"] = "5",
		["faction"] = "1",
		["hideui"] = "1",
	  },
	  ["buffs"] = {
		["debuffrowsize"] = "8",
	  },
	  ["chat"] = {
		["global"] = {
		  ["border"] = "0.1,0.1,0.1,0",
		  ["tabmouse"] = "1",
		  ["combathide"] = "0",
		  ["custombg"] = "1",
		  ["fadeout"] = "1",
		  ["background"] = "0,0,0,0",
		},
		["text"] = {
		  ["time"] = "1",
		  ["input_width"] = "380",
		  ["mouseover"] = "1",
		  ["timeformat"] = "%H:%M",
		},
		["left"] = {
		  ["height"] = "220",
		},
		["right"] = {
		  ["enable"] = "1",
		  ["alwaysshow"] = "1",
		  ["height"] = "220",
		},
	  },
	  ["disabled"] = {
		["skin_Auctionhouse"] = "0",
		["pixelperfect"] = "0",
		["skin_Spellbook"] = "0",
		["skin_Options - Sound"] = "0",
		["target"] = "0",
		["tooltip"] = "0",
		["hdgraphic"] = "0",
		["player"] = "0",
		["skin_Character Turtle"] = "0",
		["updatenotify"] = "0",
		["hunterbar"] = "0",
		["skin_Color Picker"] = "0",
		["targettargettarget"] = "0",
		["turtle-customcasts"] = "0",
		["mapreveal"] = "0",
		["bags"] = "1",
		["skin_Bagshui"] = "0",
		["chat"] = "0",
		["autoshift"] = "0",
		["skin_Battlefield"] = "0",
		["skin_Static popups Turtle"] = "0",
		["raid"] = "0",
		["Gryphons"] = "0",
		["autoinvite"] = "0",
		["skin_Looking for turtles"] = "0",
		["targettarget"] = "0",
		["sellvalue"] = "0",
		["managems"] = "0",
		["skin_Opacity"] = "0",
		["mirrortimers"] = "0",
		["share"] = "0",
		["darkmod"] = "0",
		["buff"] = "0",
		["skin_Books"] = "0",
		["debuffmonitor"] = "0",
		["skin_Battlefield Minimap"] = "0",
		["uf_tukui"] = "0",
		["skin_Trade"] = "0",
		["skin_Guild Bank Turtle"] = "0",
		["infight"] = "0",
		["questitem"] = "0",
		["skin_Friends"] = "0",
		["thirdparty"] = "0",
		["whisperproxy"] = "0",
		["mapcolors"] = "0",
		["eqcompare"] = "0",
		["tradeskillcd"] = "0",
		["addonbuttons"] = "0",
		["protraitenhance"] = "0",
		["skin_Battlefield Score"] = "0",
		["panel"] = "0",
		["rainbowhealthbar"] = "0",
		["hoverbind"] = "0",
		["itemclick"] = "0",
		["pettarget"] = "0",
		["firstrun"] = "0",
		["skin_Readycheck"] = "0",
		["cooldown"] = "0",
		["skin_Quest Log"] = "0",
		["totems"] = "0",
		["skin_Merchant"] = "0",
		["skin_KeyBindings"] = "0",
		["unlock"] = "0",
		["loot"] = "0",
		["feigndeath"] = "0",
		["chatcopy"] = "0",
		["map"] = "0",
		["skin_Trainer"] = "0",
		["skin_Profession"] = "0",
		["skin_Talents"] = "0",
		["buffwatch"] = "0",
		["socialmod"] = "0",
		["turtle-wow"] = "0",
		["focus"] = "0",
		["thirdparty-vanilla"] = "0",
		["addonskinner"] = "0",
		["skin_Guild Registrar"] = "0",
		["skin_Stack Split"] = "0",
		["skin_Help"] = "0",
		["skin_Everlook Broadcasting Turtle"] = "0",
		["skin_Tutorial"] = "0",
		["skin_Options - Interface"] = "0",
		["skin_Pet Stable Master"] = "0",
		["bubbles"] = "0",
		["damagemeter"] = "0",
		["easteregg"] = "0",
		["skin_Guild Tabard"] = "0",
		["skin_Coin Pickup"] = "0",
		["lootfilter"] = "0",
		["xpbar"] = "0",
		["addons"] = "0",
		["mouseover"] = "0",
		["macrotweak"] = "0",
		["skin_GM Survey"] = "0",
		["turtle-selldata"] = "0",
		["screenshot"] = "0",
		["skin_Inspect Turtle"] = "0",
		["gm"] = "0",
		["energytick"] = "0",
		["turtle-customdedebuffs"] = "0",
		["unusable"] = "0",
		["skin_Game Menu"] = "0",
		["skin_Options - Video"] = "0",
		["skin_Macro"] = "0",
		["group"] = "0",
		["farmmode"] = "0",
		["skin_Gossip and Quest"] = "0",
		["minimap"] = "0",
		["pet"] = "0",
		["addoncompat"] = "0",
		["skin_Character"] = "0",
		["skin"] = "0",
		["roll"] = "0",
		["skin_Inspect"] = "0",
		["superwow"] = "0",
		["skin_Quest Timer"] = "0",
		["EliteOverlay"] = "0",
		["skin_Petition"] = "0",
		["castbar"] = "0",
		["skin_Flightmaster"] = "0",
		["skin_Mailbox"] = "0",
		["PvPOverlay"] = "0",
		["autovendor"] = "0",
		["skin_Dress Up Frame"] = "0",
		["skin_Popup Dialogs"] = "0",
		["afkcam"] = "1",
		["custom"] = "0",
		["combopoints"] = "0",
		["nameplates"] = "0",
		["skin_Tooltips"] = "0",
		["tracking"] = "0",
		["actionbar"] = "0",
	  },
	  ["global"] = {
		["pixelperfect"] = "8",
		["font_combat"] = "Interface\\AddOns\\pfUI\\fonts\\Myriad-Pro.ttf",
		["font_unit"] = "Interface\\AddOns\\pfUI\\fonts\\Myriad-Pro.ttf",
		["autorepair"] = "1",
		["errors_hide"] = "1",
		["twentyfour"] = "0",
		["profile"] = "Warlock",
		["font_unit_size"] = "11",
		["font_size"] = "13",
		["autosell"] = "1",
	  },
	  ["debuffmon"] = {
		["report"] = "1",
		["hide_solo"] = "0",
		["show"] = "target",
		["width"] = "-1",
		["font_size"] = "-1",
		["report_chat"] = "SELF",
		["alive"] = "1",
		["resistances"] = "1",
		["armor"] = "1",
		["background"] = "0",
		["name"] = "0",
		["debuff"] = {
		  ["ev"] = "1",
		  ["cy"] = "1",
		  ["ff"] = "1",
		  ["ad"] = "1",
		  ["ea"] = "1",
		  ["nf"] = "1",
		  ["sw"] = "1",
		  ["coe"] = "1",
		  ["ig"] = "1",
		  ["sa"] = "1",
		  ["cor"] = "1",
		  ["sc"] = "1",
		  ["sb"] = "1",
		  ["as"] = "1",
		  ["cos"] = "1",
		  ["wc"] = "1",
		  ["ve"] = "1",
		},
	  },
	  ["PvPOverlay"] = {
		["position"] = "off",
	  },
	  ["lootfilter"] = {
		["test"] = {
		  ["test"] = "HELLO",
		},
		["delete"] = {
		  ["list_ids"] = "",
		  ["notification"] = "1",
		},
		["vendor"] = {
		  ["list_ids"] = "",
		  ["notification"] = "1",
		},
	  },
	  ["Gryphons"] = {
		["left_color"] = "0.4,0.4,0.4,1",
		["img_sizert"] = "60",
		["h_off"] = "-400",
		["right_color"] = "0.4,0.4,0.4,1",
		["img_size"] = "100",
		["h_offrt"] = "475",
		["righttop_color"] = "0.5,0.5,0.5,1",
		["img_size1"] = "100",
		["h_offlt"] = "-475",
		["h_off1"] = "400",
		["selectlefttop"] = "Gargoyle1",
		["v_off"] = "-35",
		["lefttop_color"] = "0.5,0.5,0.5,1",
		["selectright"] = "Skull",
		["img_sizelt"] = "60",
		["selectleft"] = "Skull",
		["v_offlt"] = "-315",
		["v_off1"] = "-35",
		["v_offrt"] = "-315",
		["selectrighttop"] = "Gargoyle2",
	  },
	  ["tradecd"] = {
		["startup_announce"] = "1",
		["noti_ready_rw"] = "1",
		["noti_chat"] = "1",
		["button"] = "default",
		["show_remaining"] = "1",
		["noti_ready_sound"] = "1",
		["show_current"] = "0",
	  },
	  ["panel"] = {
		["right"] = {
		  ["right"] = "infernalstone",
		  ["center"] = "demonicfigurine",
		  ["left"] = "soulshard",
		},
		["xp"] = {
		  ["rep_position"] = "TOP",
		  ["xp_width"] = "4",
		  ["rep_display"] = "DISABLED",
		  ["xp_anchor"] = "__NONONIL__",
		  ["rep_anchor"] = "__NONONIL__",
		  ["xp_height"] = "52",
		  ["xp_position"] = "TOP",
		  ["rep_height"] = "52",
		  ["xp_color"] = "0.6,0.6,0.6,1",
		  ["dont_overlap"] = "1",
		  ["rest_color"] = "0.4,0.4,0.4,0.5",
		  ["rep_width"] = "4",
		},
		["left"] = {
		  ["right"] = "durability",
		  ["center"] = "time",
		  ["left"] = "fps",
		},
	  },
	  ["addonskinner"] = {
		["notifications"] = "0",
		["disabled"] = {
		  ["ModifiedPowerAuras"] = "0",
		  ["TradesBar"] = "0",
		  ["BookStore"] = "0",
		  ["SP_Overpower"] = "0",
		  ["AutoProfit"] = "0",
		  ["Thaliz"] = "0",
		  ["TrinketMenu"] = "0",
		  ["Atlas"] = "0",
		  ["BigWigs"] = "0",
		  ["shootyepgp"] = "0",
		  ["RABuffs"] = "0",
		  ["Decursive"] = "0",
		  ["ItemRack"] = "0",
		  ["SuperMacro"] = "0",
		  ["EQL3"] = "0",
		  ["ignitestatus"] = "0",
		  ["raidTemplate"] = "0",
		  ["ItemHints"] = "0",
		  ["TurtleCount"] = "0",
		  ["CallToArms"] = "0",
		  ["TimeManager"] = "0",
		  ["AtlasLoot"] = "0",
		  ["LevelRange"] = "0",
		  ["TalentSequence"] = "0",
		  ["SuperIgnore"] = "0",
		  ["CloseUp"] = "0",
		  ["ZHunterMod"] = "0",
		  ["SuperInspect_UI"] = "0",
		  ["YaHT"] = "0",
		  ["RingMenu"] = "0",
		  ["AdvancedTradeskillWindow"] = "0",
		  ["MTLove"] = "0",
		  ["ColorPickerPlus"] = "0",
		  ["GearMenu"] = "0",
		  ["SP_SwingTimer"] = "0",
		  ["pfQuest"] = "0",
		  ["BugSack"] = "0",
		  ["Possessions"] = "0",
		  ["LoseControl"] = "0",
		  ["ES_GuildCheckGUI"] = "0",
		  ["AtlasQuest"] = "0",
		  ["TurtleZoneCount"] = "0",
		},
	  },
	  ["appearance"] = {
		["infight"] = {
		  ["intensity"] = "32",
		  ["aggro"] = "1",
		},
		["castbar"] = {
		  ["channelcolor"] = "0.9,0.4,0.5,0.8",
		  ["castbarcolor"] = "0.7,0.2,0.7,0.6",
		},
		["worldmap"] = {
		  ["mapexploration"] = "1",
		  ["mapreveal"] = "1",
		},
		["bags"] = {
		  ["bagrowlength"] = "12",
		  ["bankrowlength"] = "12",
		  ["hidechat"] = "1",
		},
		["border"] = {
		  ["shadow"] = "1",
		  ["color"] = "0,0,0,1",
		  ["bags"] = "0",
		  ["default"] = "1",
		  ["nameplates"] = "1",
		  ["background"] = "0,0,0,0.9",
		},
		["minimap"] = {
		  ["coordsloc"] = "topleft",
		  ["mouseoverzone"] = "0",
		},
	  },
	  ["castbar"] = {
		["player"] = {
		  ["width"] = "300",
		  ["showlag"] = "1",
		  ["height"] = "5",
		},
		["focus"] = {
		  ["width"] = "110",
		  ["height"] = "10",
		  ["showname"] = "0",
		},
		["target"] = {
		  ["height"] = "18",
		},
	  },
	  ["autoinvite"] = {
		["wchat"] = "1",
		["group_type"] = "raid",
		["state"] = "0",
		["notification"] = "1",
		["match_case"] = "0",
		["guild_only"] = "1",
		["phrase"] = "",
		["gchat"] = "0",
	  },
	  ["tooltip"] = {
		["questitem"] = {
		  ["showcount"] = "1",
		},
		["cursoroffset"] = "30",
		["position"] = "cursor",
		["cursoralign"] = "right",
	  },
	  ["thirdparty"] = {
		["recount"] = {
		  ["dock"] = "1",
		  ["skin"] = "1",
		},
		["shagudps"] = {
		  ["skin"] = "1",
		},
		["dpsmate"] = {
		  ["dock"] = "1",
		  ["skin"] = "1",
		},
		["swstats"] = {
		  ["dock"] = "1",
		  ["skin"] = "1",
		},
		["ktm"] = {
		  ["dock"] = "1",
		  ["skin"] = "1",
		},
		["omen"] = {
		  ["dock"] = "1",
		  ["skin"] = "1",
		},
	  },
	  ["abuttons"] = {
		["position"] = "left",
		["hideincombat"] = "0",
		["showdefault"] = "1",
	  },
	  ["buffbar"] = {
		["tdebuff"] = {
		  ["whitelist"] = "#Corruption#Curse of Agony#Immolate#Curse of Shadow#Curse of Doom#Curse of Tongues#Curse of Weakness#Curse of Recklessness#Siphon Life#Curse of the Elements#Curse of Exhaustion",
		  ["threshold"] = "300",
		  ["filter"] = "whitelist",
		},
	  },
	  ["version"] = "5.4.12",
	  ["position"] = {
		["QuestTimerFrame"] = {
		  ["xpos"] = -274,
		  ["anchor"] = "TOP",
		  ["ypos"] = -15,
		  ["parent"] = "UIParent",
		},
		["pfDurability"] = {
		  ["xpos"] = -390,
		  ["anchor"] = "BOTTOMRIGHT",
		  ["ypos"] = 40,
		  ["parent"] = "UIParent",
		},
		["pfPartyPet1"] = {
		  ["xpos"] = 460,
		  ["parent"] = "UIParent",
		  ["ypos"] = 230,
		  ["anchor"] = "BOTTOMLEFT",
		},
		["pfBank"] = {
		  ["xpos"] = 4,
		  ["anchor"] = "TOPLEFT",
		  ["ypos"] = -388,
		  ["parent"] = "UIParent",
		},
		["pfActionBarStanceBar4"] = {
		  ["xpos"] = -480,
		  ["parent"] = "UIParent",
		  ["ypos"] = 40,
		  ["anchor"] = "BOTTOMRIGHT",
		},
		["pfTarget"] = {
		  ["xpos"] = 190,
		  ["anchor"] = "BOTTOM",
		  ["ypos"] = 300,
		  ["parent"] = "UIParent",
		},
		["pfActionBarPet"] = {
		  ["xpos"] = 0,
		  ["anchor"] = "BOTTOM",
		  ["ypos"] = 94,
		  ["parent"] = "UIParent",
		},
		["pfPlayer"] = {
		  ["xpos"] = -190,
		  ["anchor"] = "BOTTOM",
		  ["ypos"] = 300,
		  ["parent"] = "UIParent",
		},
		["pfDebuffFrame"] = {
		  ["xpos"] = 0,
		  ["parent"] = "UIParent",
		  ["ypos"] = -15,
		  ["anchor"] = "CENTER",
		},
		["MirrorTimer3"] = {
		  ["xpos"] = -460,
		  ["anchor"] = "TOPRIGHT",
		  ["ypos"] = -355,
		  ["parent"] = "UIParent",
		},
		["pfTargetTarget"] = {
		  ["xpos"] = 133,
		  ["anchor"] = "BOTTOM",
		  ["ypos"] = 256,
		  ["parent"] = "UIParent",
		},
		["TicketStatusFrame"] = {
		  ["xpos"] = 385,
		  ["anchor"] = "TOPLEFT",
		  ["ypos"] = -15,
		  ["parent"] = "UIParent",
		},
		["pfActionBarPaging"] = {
		  ["xpos"] = 0,
		  ["anchor"] = "BOTTOM",
		  ["ypos"] = 67,
		  ["parent"] = "UIParent",
		},
		["pfDamageMeter"] = {
		  ["xpos"] = 1713,
		  ["parent"] = "UIParent",
		  ["ypos"] = -673,
		  ["anchor"] = "TOPLEFT",
		},
		["pfCombo4"] = {
		  ["xpos"] = 1034,
		  ["parent"] = "UIParent",
		  ["ypos"] = -755,
		  ["anchor"] = "TOPLEFT",
		},
		["pfActionBarVertical"] = {
		  ["xpos"] = -2,
		  ["parent"] = "UIParent",
		  ["ypos"] = 55,
		  ["anchor"] = "RIGHT",
		},
		["pfTargetCastbar"] = {
		  ["xpos"] = 190,
		  ["anchor"] = "BOTTOM",
		  ["ypos"] = 300,
		  ["parent"] = "UIParent",
		},
		["pfBag"] = {
		  ["xpos"] = 1536,
		  ["parent"] = "UIParent",
		  ["ypos"] = -673,
		  ["anchor"] = "TOPLEFT",
		},
		["pfLootRollFrame2"] = {
		  ["xpos"] = 0,
		  ["parent"] = "UIParent",
		  ["ypos"] = -245,
		  ["anchor"] = "TOP",
		},
		["pfUITimer"] = {
		  ["xpos"] = 0,
		  ["anchor"] = "CENTER",
		  ["ypos"] = 145,
		  ["parent"] = "UIParent",
		},
		["pfGroup3"] = {
		  ["xpos"] = 550,
		  ["parent"] = "UIParent",
		  ["ypos"] = 400,
		  ["anchor"] = "BOTTOMLEFT",
		},
		["WorldMapFrame"] = {
		  ["xpos"] = 17,
		  ["scale"] = 0.69999998807907,
		  ["ypos"] = -11,
		  ["alpha"] = 1,
		  ["anchor"] = "TOPLEFT",
		},
		["pfTooltipAnchor"] = {
		  ["xpos"] = 0,
		  ["anchor"] = "BOTTOMRIGHT",
		  ["ypos"] = 0,
		  ["parent"] = "UIParent",
		},
		["pfMinimap"] = {
		  ["xpos"] = -2,
		  ["anchor"] = "TOPRIGHT",
		  ["ypos"] = -2,
		  ["parent"] = "UIParent",
		},
		["pfActionBarStanceBar2"] = {
		  ["xpos"] = 480,
		  ["anchor"] = "BOTTOMLEFT",
		  ["ypos"] = 40,
		  ["parent"] = "UIParent",
		},
		["pfPanelMinimap"] = {
		  ["xpos"] = -2,
		  ["parent"] = "UIParent",
		  ["ypos"] = -121,
		  ["anchor"] = "TOPRIGHT",
		},
		["MirrorTimer1"] = {
		  ["xpos"] = -460,
		  ["anchor"] = "TOPRIGHT",
		  ["ypos"] = -305,
		  ["parent"] = "UIParent",
		},
		["pfFocusTarget"] = {
		  ["xpos"] = 323,
		  ["anchor"] = "BOTTOM",
		  ["ypos"] = 256,
		  ["parent"] = "UIParent",
		},
		["pfPartyPet3"] = {
		  ["xpos"] = 460,
		  ["parent"] = "UIParent",
		  ["ypos"] = 310,
		  ["anchor"] = "BOTTOMLEFT",
		},
		["pfActionBarLeft"] = {
		  ["xpos"] = -350,
		  ["anchor"] = "BOTTOM",
		  ["ypos"] = 1,
		  ["parent"] = "UIParent",
		},
		["pfReputationBar"] = {
		  ["xpos"] = -303,
		  ["parent"] = "UIParent",
		  ["ypos"] = 300,
		  ["anchor"] = "BOTTOM",
		},
		["pfLootRollFrame4"] = {
		  ["xpos"] = 0,
		  ["parent"] = "UIParent",
		  ["ypos"] = -340,
		  ["anchor"] = "TOP",
		},
		["pfCombo3"] = {
		  ["xpos"] = 1034,
		  ["parent"] = "UIParent",
		  ["ypos"] = -746,
		  ["anchor"] = "TOPLEFT",
		},
		["pfBuffFrame"] = {
		  ["xpos"] = 0,
		  ["parent"] = "UIParent",
		  ["ypos"] = 125,
		  ["anchor"] = "BOTTOM",
		},
		["pfRaidCluster"] = {
		  ["xpos"] = 525,
		  ["parent"] = "UIParent",
		  ["ypos"] = 300,
		  ["anchor"] = "BOTTOMLEFT",
		},
		["pfActionBarStanceBar1"] = {
		  ["xpos"] = 480,
		  ["anchor"] = "BOTTOMLEFT",
		  ["ypos"] = 63,
		  ["parent"] = "UIParent",
		},
		["pfGroup1"] = {
		  ["xpos"] = 550,
		  ["parent"] = "UIParent",
		  ["ypos"] = 300,
		  ["anchor"] = "BOTTOMLEFT",
		},
		["pfTargetDebuffBar"] = {
		  ["xpos"] = -430,
		  ["parent"] = "UIParent",
		  ["ypos"] = 285,
		  ["anchor"] = "BOTTOMRIGHT",
		},
		["pfCombo2"] = {
		  ["xpos"] = 1034,
		  ["parent"] = "UIParent",
		  ["ypos"] = -737,
		  ["anchor"] = "TOPLEFT",
		},
		["pfGroup2"] = {
		  ["xpos"] = 550,
		  ["parent"] = "UIParent",
		  ["ypos"] = 350,
		  ["anchor"] = "BOTTOMLEFT",
		},
		["pfParty2Target"] = {
		  ["xpos"] = 495,
		  ["parent"] = "UIParent",
		  ["ypos"] = 350,
		  ["anchor"] = "BOTTOMLEFT",
		},
		["pfLootRollFrame1"] = {
		  ["xpos"] = 0,
		  ["parent"] = "UIParent",
		  ["ypos"] = -195,
		  ["anchor"] = "TOP",
		},
		["MirrorTimer2"] = {
		  ["xpos"] = -460,
		  ["anchor"] = "TOPRIGHT",
		  ["ypos"] = -330,
		  ["parent"] = "UIParent",
		},
		["pfLootRollFrame3"] = {
		  ["xpos"] = 0,
		  ["anchor"] = "TOP",
		  ["ypos"] = -295,
		  ["parent"] = "UIParent",
		},
		["pfTotems"] = {
		  ["xpos"] = 0,
		  ["anchor"] = "BOTTOM",
		  ["ypos"] = 305,
		  ["parent"] = "UIParent",
		},
		["pfPartyPet2"] = {
		  ["xpos"] = 460,
		  ["parent"] = "UIParent",
		  ["ypos"] = 270,
		  ["anchor"] = "BOTTOMLEFT",
		},
		["pfActionBarTop"] = {
		  ["xpos"] = 0,
		  ["parent"] = "UIParent",
		  ["ypos"] = 1,
		  ["anchor"] = "BOTTOM",
		},
		["pfParty1Target"] = {
		  ["xpos"] = 495,
		  ["parent"] = "UIParent",
		  ["ypos"] = 300,
		  ["anchor"] = "BOTTOMLEFT",
		},
		["pfFocus"] = {
		  ["xpos"] = 243,
		  ["parent"] = "UIParent",
		  ["ypos"] = 256,
		  ["anchor"] = "BOTTOM",
		},
		["pfActionBarStances"] = {
		  ["xpos"] = 0,
		  ["parent"] = "UIParent",
		  ["ypos"] = -129,
		  ["anchor"] = "CENTER",
		},
		["pfPetTarget"] = {
		  ["xpos"] = -137,
		  ["anchor"] = "BOTTOM",
		  ["ypos"] = 263,
		  ["parent"] = "UIParent",
		},
		["pfPet"] = {
		  ["xpos"] = -248,
		  ["anchor"] = "BOTTOM",
		  ["ypos"] = 256,
		  ["parent"] = "UIParent",
		},
		["pfTargetTargetTarget"] = {
		  ["xpos"] = 59,
		  ["parent"] = "UIParent",
		  ["ypos"] = 256,
		  ["anchor"] = "BOTTOM",
		},
		["pfCombo5"] = {
		  ["xpos"] = 1034,
		  ["parent"] = "UIParent",
		  ["ypos"] = -764,
		  ["anchor"] = "TOPLEFT",
		},
		["pfParty3Target"] = {
		  ["xpos"] = 495,
		  ["parent"] = "UIParent",
		  ["ypos"] = 400,
		  ["anchor"] = "BOTTOMLEFT",
		},
		["pfExperienceBar"] = {
		  ["xpos"] = -303,
		  ["parent"] = "UIParent",
		  ["ypos"] = 300,
		  ["anchor"] = "BOTTOM",
		},
		["pfCombo1"] = {
		  ["xpos"] = 1034,
		  ["parent"] = "UIParent",
		  ["ypos"] = -728,
		  ["anchor"] = "TOPLEFT",
		},
		["pfActionBarMain"] = {
		  ["xpos"] = 0,
		  ["anchor"] = "BOTTOM",
		  ["ypos"] = 34,
		  ["parent"] = "UIParent",
		},
		["pfPartyPet4"] = {
		  ["xpos"] = 460,
		  ["parent"] = "UIParent",
		  ["ypos"] = 350,
		  ["anchor"] = "BOTTOMLEFT",
		},
		["pfParty4Target"] = {
		  ["xpos"] = 495,
		  ["parent"] = "UIParent",
		  ["ypos"] = 450,
		  ["anchor"] = "BOTTOMLEFT",
		},
		["pfFocusCastbar"] = {
		  ["xpos"] = 243,
		  ["anchor"] = "BOTTOM",
		  ["ypos"] = 256,
		  ["parent"] = "UIParent",
		},
		["pfActionBarRight"] = {
		  ["xpos"] = 350,
		  ["anchor"] = "BOTTOM",
		  ["ypos"] = 1,
		  ["parent"] = "UIParent",
		},
		["pfPlayerCastbar"] = {
		  ["xpos"] = 0,
		  ["parent"] = "UIParent",
		  ["ypos"] = -110,
		  ["anchor"] = "CENTER",
		},
		["pfGroup4"] = {
		  ["xpos"] = 550,
		  ["anchor"] = "BOTTOMLEFT",
		  ["ypos"] = 450,
		  ["parent"] = "UIParent",
		},
		["pfActionBarStanceBar3"] = {
		  ["xpos"] = -480,
		  ["anchor"] = "BOTTOMRIGHT",
		  ["ypos"] = 63,
		  ["parent"] = "UIParent",
		},
		["pfChatInputBox"] = {
		  ["xpos"] = 0,
		  ["anchor"] = "BOTTOM",
		  ["ypos"] = 125,
		  ["parent"] = "UIParent",
		},
	  },
	  ["nameplates"] = {
		["friendlyplayer"] = "1",
		["target"] = "0",
		["targetzoomval"] = ".50",
		["cpdisplay"] = "1",
		["use_unitfonts"] = "1",
		["fullhealth"] = "0",
		["targethighlight"] = "1",
		["heighthealth"] = "15",
		["friendclassnamec"] = "1",
		["spellname"] = "1",
		["friendlynpc"] = "1",
		["totemicons"] = "1",
		["highlightcolor"] = "0,0,0,1",
		["width"] = "150",
		["health"] = {
		  ["offset"] = "14",
		},
		["targetzoom"] = "1",
		["overlap"] = "1",
	  },
	  ["bars"] = {
		["bar3"] = {
		  ["showmacro"] = "0",
		  ["formfactor"] = "12 x 1",
		  ["icon_size"] = "24",
		  ["showempty"] = "0",
		  ["showcount"] = "0",
		},
		["rightself"] = "1",
		["bar9"] = {
		  ["enable"] = "1",
		  ["showempty"] = "0",
		  ["background"] = "0",
		},
		["count_color"] = ".2,1,.8,1",
		["animation"] = "shrinkreturn",
		["bar1"] = {
		  ["showmacro"] = "0",
		  ["icon_size"] = "28",
		  ["showempty"] = "0",
		  ["showcount"] = "0",
		},
		["keydown"] = "1",
		["bar7"] = {
		  ["enable"] = "1",
		  ["showempty"] = "0",
		  ["background"] = "0",
		},
		["animalways"] = "1",
		["bar12"] = {
		  ["showkeybind"] = "0",
		  ["icon_size"] = "22",
		  ["showempty"] = "0",
		},
		["bar10"] = {
		  ["enable"] = "1",
		  ["showempty"] = "0",
		  ["background"] = "0",
		},
		["bar4"] = {
		  ["showmacro"] = "0",
		  ["hide_combat"] = "0",
		  ["showkeybind"] = "0",
		  ["buttons"] = "10",
		  ["icon_size"] = "25",
		  ["formfactor"] = "1 x 10",
		  ["autohide"] = "1",
		  ["hide_time"] = "1",
		},
		["bar11"] = {
		  ["enable"] = "0",
		  ["showkeybind"] = "0",
		},
		["altself"] = "1",
		["bar2"] = {
		  ["showmacro"] = "0",
		  ["hide_combat"] = "0",
		  ["enable"] = "1",
		  ["icon_size"] = "22",
		  ["pageable"] = "0",
		  ["showcount"] = "0",
		  ["hide_time"] = "1",
		},
		["bar5"] = {
		  ["showmacro"] = "0",
		  ["formfactor"] = "12 x 1",
		  ["icon_size"] = "24",
		  ["showempty"] = "0",
		  ["showcount"] = "0",
		},
		["bar8"] = {
		  ["enable"] = "1",
		  ["showempty"] = "0",
		  ["background"] = "0",
		},
		["bar6"] = {
		  ["showmacro"] = "0",
		  ["icon_size"] = "28",
		  ["showempty"] = "0",
		  ["showcount"] = "0",
		},
	  },
	  ["EliteOverlay"] = {
		["position"] = "right",
	  },
	  ["gui"] = {
		["reloadmarker"] = "1",
	  },
  }

  -- create gui entries for each option
  CreateGUIEntry(T["Thirdparty"], T["darkmod"], function()
    CreateConfig(nil, "Move Chat Frames", C.darkmod, "movechat", "checkbox")
    CreateConfig(nil, "Draw Dark Bottom Line", C.darkmod, "darkline", "checkbox")
    CreateConfig(nil, "Strech Viewport", C.darkmod, "viewport", "checkbox")
    CreateConfig(nil, "Autosize and Move Chat Input Box", C.darkmod, "chatbox", "checkbox")
    CreateConfig(nil, "Autosize and Move Castbar", C.darkmod, "castbar", "checkbox")
    CreateConfig(nil, "Autosize and Move XP/Reputation", C.darkmod, "movexp", "checkbox")
    CreateConfig(nil, "Move Buffs", C.darkmod, "movebuff", "checkbox")
    CreateConfig(nil, "Autosize and Move Minimap", C.darkmod, "minimap", "checkbox")
    CreateConfig(nil, "Move Actionbars", C.darkmod, "actionbar", "checkbox")
    CreateConfig(nil, "Move UnitFrames", C.darkmod, "unitframe", "checkbox")
    CreateConfig(nil, "Merge Tracking Icon Into Chat-Tab", C.darkmod, "tracking", "checkbox")
    CreateConfig(nil, "Move Loot Rolls", C.darkmod, "lootrolls", "checkbox")
    CreateConfig(nil, "Create Top Panel Background", C.darkmod, "topbg", "checkbox")
  end)

  -- make sure that all required modules are loaded. otherwise break and print a message
  if not pfUI.chat or not pfUI.castbar or not pfUI.rep or not pfUI.xp or not
    pfUI.buff or not pfUI.minimap or not pfUI.bars or not pfUI.tracking or not
    pfUI.thirdparty or not pfUI.uf or not pfUI.uf.player or not pfUI.uf.target or not
    pfUI.uf.targettarget or not pfUI.uf.raid or not pfUI.uf.group
  then
    message("|cff33aa88darkmod|r has been disabled. Not all required pfUI modules were loaded")
    message("Reset your config to the defaults and load the \"pfUI [|cff33aa88darkmod|r]\" profile")
    return
  end

  -- define and calculate some basic variables to safe some space later.
  local border = tonumber(pfUI_config.appearance.border.default)
  local aborder = tonumber(C.appearance.border.actionbars) == -1 and border or tonumber(C.appearance.border.actionbars)
  local bpad = border > 1 and 1 or 0

  -- Move Chat Frames
  --   move left chat to the bottomleft without padding.
  --   move right chat to the bottomleft without padding.
  if C.darkmod.movechat == "1" then
    pfUI.chat.left:SetPoint("BOTTOMLEFT", UIParent, "BOTTOMLEFT", 0, 0)
    UpdateMovable(pfUI.chat.left, true)

    pfUI.chat.right:SetPoint("BOTTOMRIGHT", UIParent, "BOTTOMRIGHT", 0, 0)
    UpdateMovable(pfUI.chat.right, true)
  end

  -- Draw Dark Bottom Line
  --   add a black gradient to the bottom and stretch it up to the chat-tab-bar.
  if C.darkmod.darkline == "1" then
    local bottom = CreateFrame("Frame", nil, UIParent)
    bottom:SetFrameStrata("BACKGROUND")
    bottom:SetPoint("LEFT", UIParent, "LEFT", 0, 0)
    bottom:SetPoint("RIGHT", UIParent, "RIGHT", 0, 0)
    bottom:SetPoint("BOTTOM", UIParent, "BOTTOM", 0, 0)
    bottom:SetPoint("TOP", pfUI.chat.left.panelTop.backdrop, "BOTTOM", 0, -bpad)
    bottom.tex = bottom:CreateTexture("pfGradient", "BACKGROUND")
    bottom.tex:SetAllPoints(bottom)
    bottom.tex:SetTexture(0,0,0,1)
    bottom.tex:SetGradientAlpha("VERTICAL", 0,0,0,1,  0,0,0,0)
    CreateBackdrop(bottom, nil, nil, .65)
  end

  -- Strech Viewport
  --   stretch the viewport by cutting off a few pixels at the bottom to not have
  --   the bottom gradient eat too much space and have the character more centered.
  if C.darkmod.viewport == "1" then
    WorldFrame:ClearAllPoints();
    WorldFrame:SetPoint("TOP", UIParent, "TOP", 0, 0)
    WorldFrame:SetPoint("LEFT", UIParent, "LEFT", 0, 0)
    WorldFrame:SetPoint("RIGHT", UIParent, "RIGHT", 0, 0)
    WorldFrame:SetPoint("BOTTOM", pfUI.bars[1], "TOP", 0, 0)
  end

  -- Autosize and Move Chat Input Box
  --   make chatinput box fit between chat docks.
  if C.darkmod.chatbox == "1" then
    pfUI.chat.editbox:ClearAllPoints()
    pfUI.chat.editbox:SetPoint("TOPLEFT", pfUI.chat.left.panelTop, "TOPRIGHT", border*2, 0)
    pfUI.chat.editbox:SetPoint("BOTTOMRIGHT", pfUI.chat.right.panelTop, "BOTTOMLEFT", -border*2, 0)
    CreateBackdrop(ChatFrameEditBox, nil, nil, .8)
    UpdateMovable(pfUI.chat.editbox, true)
  end

  -- Autosize and Move Castbar
  --   make the castbar fit between both chat docks.
  --   move the target castbar into the center of the screen.
  if C.darkmod.castbar == "1" then
    pfChatArrange:SetScript("OnEvent", nil)
    pfUI.castbar.player:ClearAllPoints()
    pfUI.castbar.player:SetPoint("TOPLEFT", pfUI.chat.left.panelTop, "TOPRIGHT", border*2, 0)
    pfUI.castbar.player:SetPoint("BOTTOMRIGHT", pfUI.chat.right.panelTop, "BOTTOMLEFT", -border*2, 0)
    CreateBackdrop(pfUI.castbar.player, nil, nil, .8)
    UpdateMovable(pfUI.castbar.player, true)

    pfUI.castbar.target:ClearAllPoints()
    pfUI.castbar.target:SetPoint("CENTER", 0, -150)
    pfUI.castbar.target:SetWidth(250)
    pfUI.castbar.target:SetHeight(20)
    UpdateMovable(pfUI.castbar.target, true)
  end

  -- Autosize and Move XP/Reputation
  --   adjust xp and reputation bar height.
  if C.darkmod.movexp == "1" then
    pfUI.xp:SetPoint("TOPLEFT", pfUI.chat.left.panelTop.backdrop, "BOTTOMRIGHT", C.appearance.border.default*2, -bpad)
    pfUI.rep:SetPoint("TOPRIGHT", pfUI.chat.right.panelTop.backdrop, "BOTTOMLEFT", -C.appearance.border.default*2, -bpad)
  end

  -- Move Buffs
  --   move buffs to the topright of the screen.
  if C.darkmod.movebuff == "1" then
    pfUI.buff.buffs:ClearAllPoints()
    pfUI.buff.buffs:SetPoint("TOPRIGHT", UIParent, "TOPRIGHT", -tonumber(C.buffs.spacing), -tonumber(C.buffs.spacing))
    UpdateMovable(pfUI.buff.buffs, true)
  end

  -- Autosize and Move Minimap
  --   move the minimap to the center bottom.
  if C.darkmod.minimap == "1" then
    pfUI.minimap:ClearAllPoints()
    pfUI.minimap:SetPoint("BOTTOM", UIParent, "BOTTOM", 0, border)
    pfUI.minimap:SetScale(.8)
    pfUI.panel.minimap:SetScale(pfUI.minimap:GetScale())
    UpdateMovable(pfUI.minimap, true)
  end

  -- Move Actionbars
  --   move the main actionbar bar to the minimap.
  --   move the top actionbar above the main actionbar.
  --   move the left actionbar to the right of minimap.
  --   move the right actionbar above the left actionbar.
  --   set the position of the shapeshift/stance bars to the right of the screen.
  --   set the position of the petactionbars to the right of the screen.
  if C.darkmod.actionbar == "1" then
    pfUI.bars[1]:ClearAllPoints()
    pfUI.bars[1]:SetPoint("BOTTOMRIGHT", pfUI.minimap, "BOTTOMLEFT", -2*border, -border)
    UpdateMovable(pfUI.bars[1], true)

    pfUI.bars[6]:ClearAllPoints()
    pfUI.bars[6]:SetPoint("BOTTOM", pfUI.bars[1], "TOP", 0, -aborder)
    UpdateMovable(pfUI.bars[6], true)

    pfUI.bars[3]:ClearAllPoints()
    pfUI.bars[3]:SetPoint("BOTTOMLEFT", pfUI.minimap, "BOTTOMRIGHT", 2*border, -border)
    UpdateMovable(pfUI.bars[3], true)

    pfUI.bars[5]:ClearAllPoints()
    pfUI.bars[5]:SetPoint("BOTTOM", pfUI.bars[3], "TOP", 0, -aborder)
    UpdateMovable(pfUI.bars[5], true)

    -- as the positions get overwritten on several events, hook the OnShow function
    -- to make sure that our positions do overwrite the previous ones.
    HookScript(pfUI.bars[11], "OnEvent", function()
      pfUI.bars[11]:ClearAllPoints()

      if pfUI.bars[12]:IsShown() then
        -- align it to the pet bar if visible.
        pfUI.bars[11]:SetPoint("RIGHT", pfUI.bars[12], "LEFT", -2*border, 0)
      elseif pfUI.bars[4]:IsShown() then
        -- align it to the vertical actionbar if visible.
        pfUI.bars[11]:SetPoint("RIGHT", pfUI.bars[4], "LEFT", -2*border, 0)
      else
        -- align it to the right of the screen.
        pfUI.bars[11]:SetPoint("RIGHT", UIParent, "RIGHT", -border, 0)
      end
      UpdateMovable(pfUI.bars[11], true)
    end, true)

    -- as the positions get overwritten on several events, hook the ClearAllPoints
    -- function to make sure that our positions do overwrite the previous ones.
    HookScript(pfUI.bars[12], "OnEvent", function()
      pfUI.bars[12]:ClearAllPoints()

      if pfUI.bars[4]:IsShown() then
        -- align it to the vertical actionbar if visible.
        pfUI.bars[12]:SetPoint("RIGHT", pfUI.bars[4], "LEFT", -2*border, 0)
      else
        -- align it to the right of the screen.
        pfUI.bars[12]:SetPoint("RIGHT", UIParent, "RIGHT", -border, 0)
      end
      UpdateMovable(pfUI.bars[12], true)
    end, true)
  end

  -- Move UnitFrames
  --   move the playerframe above the left actionbars.
  --   move the targetframe above the right actionbars.
  --   move the targettargetframe above the minimap.
  --   move the pet unitframe slightly higher to not have it collide with the castbar.
  --   set the position of all raidframes to the top of the left chat panel.
  --   set the position of all groupframes to the top of the left chat panel.
  if C.darkmod.unitframe == "1" then
    pfUI.uf.player:ClearAllPoints()
    pfUI.uf.player:SetPoint("BOTTOM", pfUI.bars[6], "TOP", 0, aborder)
    UpdateMovable(pfUI.uf.player, true)

    pfUI.uf.target:ClearAllPoints()
    pfUI.uf.target:SetPoint("BOTTOM", pfUI.bars[5], "TOP", 0, aborder)
    UpdateMovable(pfUI.uf.target, true)

    pfUI.uf.targettarget:ClearAllPoints()
    pfUI.uf.targettarget:SetPoint("BOTTOM", pfUI.minimap, "TOP", 0, 2*aborder)
    UpdateMovable(pfUI.uf.targettarget, true)

    pfUI.uf.pet:ClearAllPoints()
    pfUI.uf.pet:SetPoint("BOTTOM", UIParent , "BOTTOM", 0, 175)
    UpdateMovable(pfUI.uf.pet, true)

    for r=1, 8 do
      for g=1, 5 do
        i = g + 5*(r-1)
        local spacing = pfUI.uf.raid[i].config.pspace
        local width = pfUI.uf.raid[i].config.width
        local height = pfUI.uf.raid[i].config.height
        local pheight = pfUI.uf.raid[i].config.pheight
        local real_height = height + spacing + pheight + 2*border
        pfUI.uf.raid[i]:ClearAllPoints()
        if g == 1 and math.mod(r,2) == 1 then
          pfUI.uf.raid[i]:SetPoint("BOTTOMLEFT", 2, C.chat.left.height - real_height/2 + (r/2)*(real_height+5))
        else
          pfUI.uf.raid[i]:SetPoint("LEFT", pfUI.uf.raid[i-1], "RIGHT", 5, 0)
        end
        UpdateMovable(pfUI.uf.raid[i], true)
      end
    end

    for i=1, 4 do
      pfUI.uf.group[i]:ClearAllPoints()
      if i == 1 then
        pfUI.uf.group[i]:SetPoint("BOTTOMLEFT", 2, C.chat.left.height + border)
      else
        pfUI.uf.group[i]:SetPoint("LEFT", pfUI.uf.group[i-1], "RIGHT", 5, 0)
      end

      pfUI.uf.group[i].target:ClearAllPoints()
      pfUI.uf.group[i].target:SetPoint("BOTTOM", pfUI.uf.group[i], "TOP", 0, border)

      UpdateMovable(pfUI.uf.group[i], true)
      UpdateMovable(pfUI.uf.group[i].target, true)
    end
  end

  -- Merge Tracking Icon Into Chat-Tab
  --   move/merge the tracking icon into the right chattab panel.
  --   also set its parent to make it vanish when the meters are shown.
  if C.darkmod.tracking == "1" then
    pfUI.tracking:ClearAllPoints()
    pfUI.tracking:SetParent(pfUI.chat.right.panelTop)
    pfUI.tracking:SetPoint("RIGHT", pfUI.chat.right.panelTop, "RIGHT", 0, 0)
    pfUI.tracking:SetHeight(pfUI.chat.right.panelTop:GetHeight())
    pfUI.tracking:SetWidth(pfUI.chat.right.panelTop:GetHeight())
    UpdateMovable(pfUI.tracking, true)
  end

  -- Move Loot Rolls
  --   set the position of all loot rolls to the top of the right chat panel.
  --   also decrease the spacing and make the width same as the panel.
  if C.darkmod.lootrolls == "1" then
    for i=1,4 do
      pfUI.roll.frames[i]:ClearAllPoints()
      pfUI.roll.frames[i]:SetPoint("BOTTOMRIGHT", pfUI.chat.right.panelTop, "TOPRIGHT", 0, (i-1)*(26+2*border) + 2*border)
      pfUI.roll.frames[i]:SetPoint("BOTTOMLEFT", pfUI.chat.right.panelTop, "TOPLEFT", 0, (i-1)*(26+2*border) + 2*border)
      pfUI.roll.frames[i]:SetHeight(26)
      UpdateMovable(pfUI.roll.frames[i], true)
    end
  end

  -- Create Top Panel Background
  --   create a backdrop of the size and appearance of a chat tab dock.
  --   make the new backdrop toggle when the meters are shown by hooking the
  if C.darkmod.topbg == "1" then
    local topbg = CreateFrame("Frame", "pfMetersDockTop", UIParent)
    topbg:SetFrameStrata("BACKGROUND")
    topbg:SetAllPoints(pfUI.chat.right.panelTop)
    CreateBackdrop(topbg, nil, nil, .8)
    topbg:Hide()

    -- thirdparty-module's toggle function.
    local pfHookMetersToggle = pfUI.thirdparty.meters.Toggle
    pfUI.thirdparty.meters.Toggle = function()
      if pfUI.thirdparty.meters.state == true then
        topbg:Hide()
      else
        topbg:Show()

        -- adjust the position of DPSMates total display to not have it collide with the backdrop.
        if DPSMate_DPSMate_Head and C.thirdparty.dpsmate.dock == "1" then
          DPSMate_DPSMate_Head:SetPoint("TOPLEFT", 0, -2)
          DPSMate_DPSMate_ScrollFrame_Child_Total:SetPoint("TOPLEFT", 0, -3)
        end

        -- set the height of KTMs title to not have it collide with the backdrop.
        if KLHTM_Frame and C.thirdparty.ktm.dock == "1" then
          KLHTM_TitleFrame:SetHeight(21)
        end
      end

      -- run the original function.
      pfHookMetersToggle()
    end
  end
end)
